# Site settings
author: Steven Crouse
title: The Learning Curve of Programming
header-img: img/home-bg.png
email: sdcrouse91@gmail.com
copyright_name: Steven Crouse
description: > # this means to ignore newlines until "baseurl:"
  Practical posts from a puzzle-solving programmer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Sdcrouse

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
